services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./db/.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_pgdata:/var/lib/postgresql/data
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - 3050:80
    depends_on:
      - api
      - client
  api:
    build:
      context: ./api
      target: development
    command: npm run start:dev
    volumes:
      - ./api:/usr/src/app:delegated
      - api_node_modules:/usr/src/app/node_modules
    env_file:
      - ./api/.env
    environment:
      - DATABASE_URL=postgresql://postgres:carental@postgres:5432/carental
    depends_on:
      - postgres
  client:
    build:
      context: ./client
      target: development
    command: npm run dev
    volumes:
      - ./client:/app:delegated
      - client_node_modules:/app/node_modules
      - client_assets:/app/public
    environment:
      - WDS_SOCKET_PORT=0
      - API_BASE_URL=http://api:5000

volumes:
  db_pgdata:
  api_node_modules:
  client_node_modules:
  client_assets:
