services:
  postgres:
    image: postgres
    networks:
      - carental-network
    ports:
      - 5432:5432
    env_file:
      - ./db/.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: carental # Set your own password here
      POSTGRES_DB: carental
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  nginx:
    restart: always
    image: 391898470917.dkr.ecr.ap-southeast-1.amazonaws.com/carental/nginx:latest
    networks:
      - carental-network
    ports:
      - 3000:80
    depends_on:
      - api
      - client
  api:
    image: 391898470917.dkr.ecr.ap-southeast-1.amazonaws.com/carental/api:latest
    networks:
      - carental-network
    hostname: api
    ports:
      - 3001:3000
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  client:
    image: 391898470917.dkr.ecr.ap-southeast-1.amazonaws.com/carental/client:latest
    networks:
      - carental-network
    hostname: client
    ports:
      - 3002:3000
    env_file:
      - .env
    environment:
      - WDS_SOCKET_PORT=0
      - API_BASE_URL=http://nginx/api
      - NEXT_PUBLIC_API_URL=http://nginx/api
      - NEXT_PUBLIC_BASE_URL=http://nginx

volumes:
  db_pgdata:

networks:
  carental-network:
