services:
  postgres:
    image: postgres
    networks:
      - carental-network
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_pgdata:/var/lib/postgresql/data
    entrypoint: ["./db/entrypoint.sh"]
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  nginx:
    restart: always
    image: ${AWS_ECR_REGISTRY}/carental/nginx:latest
    networks:
      - carental-network
    ports:
      - 8080:80
    depends_on:
      - api
      - client
  api:
    image: ${AWS_ECR_REGISTRY}/carental/api:latest
    networks:
      - carental-network
    hostname: api
    environment:
      - PORT=3000
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  client:
    image: ${AWS_ECR_REGISTRY}/carental/client:latest
    networks:
      - carental-network
    hostname: client
    environment:
      - WDS_SOCKET_PORT=0
      - API_BASE_URL=http://nginx/api
      - NEXT_PUBLIC_API_URL=http://nginx/api
      - NEXT_PUBLIC_BASE_URL=http://nginx
      - PORT=3000

volumes:
  db_pgdata:

networks:
  carental-network:
