{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: prisma-migrate
          image: {{ .Values.api.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              npm run deploy:prisma -- --schema=prisma/schema.prisma
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@{{ .Release.Name }}-postgresql.postgresql.svc.cluster.local:5432/carental
      containers:
        - name: api
          image: {{ .Values.api.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              npm run seed:prisma
              npm run start:prod
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@{{ .Release.Name }}-postgresql.postgresql.svc.cluster.local:5432/carental
            - name: JWT_SECRET
              value: {{ .Values.api.jwt.secret }}
            - name: JWT_EXPIRATION
              value: "{{ .Values.api.jwt.expiration }}"
            - name: PORT
              value: "{{ .Values.api.port }}"

{{- end }}
